### ISSUE TITLE
0.3.1 breaks the 0.3 API

### ISSUE THREAD

**Issue by teythoon** [emgre/win-crypto-ng#37]
We use the `eax` crate, and https://github.com/emgre/win-crypto-ng/pull/34 broke building with `eax = 0.2`.  Works fine with `eax = 0.3`.

I think the right way to recover is to release `0.4.0` and yank `0.3.1`.

**Comment by emgre** [comment]
Oh you're right, I forgot about that PR. I'll publish 0.4.0 and yank 0.3.1 shortly.

**Comment by emgre** [comment]
Done: https://crates.io/crates/win-crypto-ng/0.4.0

**Comment by teythoon** [comment]
Thanks :)
