### ISSUE TITLE
Please update to a newer version of the cipher dependency

### ISSUE THREAD

**Issue by puzzlewolf** [emgre/win-crypto-ng#41]
Hi :)

`win-crypto-ng` uses [cipher](https://crates.io/crates/cipher) version 0.2.5, while 0.4.3 has been released and most of the rust-crypto ecosystem has moved to cipher 0.4. cipher provides core traits for interoperability, so all dependencies of a project use the same version.

Please consider updating the cipher dependency, so that my downstream project ([sequoia](https://gitlab.com/sequoia-pgp/sequoia/-/issues/910)) can update its rust-crypto dependencies.

Thanks!

**Comment by emgre** [comment]
Thanks for bringing this up, I'll try to make the update shortly.

Since I have you here, do you know what is the minimum Rust version that Sequoia is targeting? I wanted to increase the minimum version, but since you are the primary user of this lib, I hold off.

**Comment by puzzlewolf** [comment]
Thank you very much!

Also thanks for considering our MSRV! Our currently stated MSRV is 1.56.1, but the Rust version in Debian testing is our upper bound, so we'll shortly move to 1.59.0. I hope that's new enough :)

**Comment by puzzlewolf** [comment]
Hi @emgre, *poke* :)

Is there something I can do to help this along?

**Comment by emostov** [comment]
@emgre any updates here?

**Comment by emgre** [comment]
Sorry for the radio silence. I'm no longer using this library for any endeavour, so I have less time to spend on it.

I'm open to pull requests if anyone is interested in tackling this.
